-- Trading Simulator Database Schema
-- PostgreSQL for Supabase

-- Users table (for multi-user support in future)
CREATE TABLE users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Portfolio table - main portfolio information
CREATE TABLE portfolios (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL DEFAULT 'Main Portfolio',
    initial_capital DECIMAL(15,2) NOT NULL DEFAULT 200.00,
    cash DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_value DECIMAL(15,2) NOT NULL DEFAULT 200.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Positions table - current stock positions
CREATE TABLE positions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    portfolio_id UUID REFERENCES portfolios(id) ON DELETE CASCADE,
    symbol VARCHAR(10) NOT NULL,
    shares DECIMAL(15,6) NOT NULL,
    entry_price DECIMAL(10,4) NOT NULL,
    current_price DECIMAL(10,4) NOT NULL,
    entry_date TIMESTAMP WITH TIME ZONE NOT NULL,
    stop_loss DECIMAL(10,4),
    take_profit DECIMAL(10,4),
    position_type VARCHAR(10) NOT NULL DEFAULT 'long', -- 'long' or 'short'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(portfolio_id, symbol) -- One position per symbol per portfolio
);

-- Trades table - all executed trades
CREATE TABLE trades (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    portfolio_id UUID REFERENCES portfolios(id) ON DELETE CASCADE,
    symbol VARCHAR(10) NOT NULL,
    side VARCHAR(4) NOT NULL, -- 'buy' or 'sell'
    shares DECIMAL(15,6) NOT NULL,
    price DECIMAL(10,4) NOT NULL,
    value DECIMAL(15,2) NOT NULL, -- shares * price
    commission DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    trade_type VARCHAR(10) NOT NULL DEFAULT 'market', -- 'market', 'limit', 'stop'
    reason TEXT,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Daily portfolio performance tracking
CREATE TABLE daily_performance (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    portfolio_id UUID REFERENCES portfolios(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    portfolio_value DECIMAL(15,2) NOT NULL,
    cash DECIMAL(15,2) NOT NULL,
    daily_pnl DECIMAL(15,2) NOT NULL,
    daily_return_percent DECIMAL(8,4) NOT NULL,
    total_return_percent DECIMAL(8,4) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(portfolio_id, date)
);

-- Trading signals generated by the system
CREATE TABLE trading_signals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL,
    signal_type VARCHAR(20) NOT NULL, -- 'strong_buy', 'buy', 'weak_buy', 'hold', 'weak_sell', 'sell', 'strong_sell'
    confidence DECIMAL(3,2) NOT NULL, -- 0.00 to 1.00
    strength DECIMAL(3,2) NOT NULL, -- 0.00 to 1.00
    current_price DECIMAL(10,4),
    target_price DECIMAL(10,4),
    stop_loss DECIMAL(10,4),
    reasoning TEXT,
    technical_score DECIMAL(3,2),
    news_score DECIMAL(3,2),
    volume_score DECIMAL(3,2),
    momentum_score DECIMAL(3,2),
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Recommendations generated by the system
CREATE TABLE recommendations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    portfolio_id UUID REFERENCES portfolios(id) ON DELETE CASCADE,
    action VARCHAR(10) NOT NULL, -- 'buy', 'sell', 'hold', 'reduce', 'add'
    symbol VARCHAR(10) NOT NULL,
    shares DECIMAL(15,6) NOT NULL,
    current_price DECIMAL(10,4) NOT NULL,
    target_price DECIMAL(10,4),
    stop_loss DECIMAL(10,4),
    reasoning TEXT NOT NULL,
    confidence DECIMAL(3,2) NOT NULL,
    urgency VARCHAR(10) NOT NULL, -- 'low', 'medium', 'high'
    expected_return DECIMAL(8,4),
    risk_level VARCHAR(10) NOT NULL, -- 'low', 'medium', 'high'
    time_horizon VARCHAR(10) NOT NULL, -- 'short', 'medium', 'long'
    status VARCHAR(20) NOT NULL DEFAULT 'pending', -- 'pending', 'executed', 'expired', 'rejected'
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    executed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Market data snapshots
CREATE TABLE market_data (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL,
    current_price DECIMAL(10,4) NOT NULL,
    volume BIGINT,
    daily_change DECIMAL(8,4),
    daily_change_percent DECIMAL(8,4),
    rsi DECIMAL(5,2),
    macd DECIMAL(8,4),
    macd_signal DECIMAL(8,4),
    sma_20 DECIMAL(10,4),
    sma_50 DECIMAL(10,4),
    bb_upper DECIMAL(10,4),
    bb_lower DECIMAL(10,4),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- News articles and sentiment analysis
CREATE TABLE news_articles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    symbol VARCHAR(10) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    url TEXT,
    source VARCHAR(100),
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    sentiment VARCHAR(10), -- 'positive', 'negative', 'neutral'
    sentiment_score DECIMAL(3,2), -- -1.00 to 1.00
    confidence DECIMAL(3,2), -- 0.00 to 1.00
    impact DECIMAL(3,2), -- 0.00 to 1.00
    processed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- System logs for tracking operations
CREATE TABLE system_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    level VARCHAR(10) NOT NULL, -- 'INFO', 'WARNING', 'ERROR', 'DEBUG'
    module VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    metadata JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Performance metrics cache
CREATE TABLE performance_metrics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    portfolio_id UUID REFERENCES portfolios(id) ON DELETE CASCADE,
    total_return DECIMAL(8,4) NOT NULL,
    annualized_return DECIMAL(8,4) NOT NULL,
    sharpe_ratio DECIMAL(8,4) NOT NULL,
    max_drawdown DECIMAL(8,4) NOT NULL,
    win_rate DECIMAL(5,2) NOT NULL,
    avg_win DECIMAL(10,4) NOT NULL,
    avg_loss DECIMAL(10,4) NOT NULL,
    profit_factor DECIMAL(8,4) NOT NULL,
    total_trades INTEGER NOT NULL,
    days_active INTEGER NOT NULL,
    risk_level VARCHAR(10) NOT NULL,
    performance_grade VARCHAR(1) NOT NULL,
    volatility DECIMAL(8,4) NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better performance
CREATE INDEX idx_positions_portfolio_id ON positions(portfolio_id);
CREATE INDEX idx_positions_symbol ON positions(symbol);
CREATE INDEX idx_trades_portfolio_id ON trades(portfolio_id);
CREATE INDEX idx_trades_symbol ON trades(symbol);
CREATE INDEX idx_trades_executed_at ON trades(executed_at);
CREATE INDEX idx_daily_performance_portfolio_date ON daily_performance(portfolio_id, date);
CREATE INDEX idx_trading_signals_symbol_generated ON trading_signals(symbol, generated_at);
CREATE INDEX idx_recommendations_portfolio_status ON recommendations(portfolio_id, status);
CREATE INDEX idx_market_data_symbol_timestamp ON market_data(symbol, timestamp);
CREATE INDEX idx_news_articles_symbol_published ON news_articles(symbol, published_at);
CREATE INDEX idx_system_logs_timestamp ON system_logs(timestamp);

-- Views for easier querying
CREATE VIEW v_portfolio_summary AS
SELECT
    p.id,
    p.name,
    p.initial_capital,
    p.cash,
    p.total_value,
    (p.total_value - p.initial_capital) as total_pnl,
    ((p.total_value - p.initial_capital) / p.initial_capital * 100) as total_return_percent,
    COUNT(pos.id) as positions_count,
    p.updated_at
FROM portfolios p
LEFT JOIN positions pos ON p.id = pos.portfolio_id
GROUP BY p.id, p.name, p.initial_capital, p.cash, p.total_value, p.updated_at;

CREATE VIEW v_current_positions AS
SELECT
    pos.id,
    pos.portfolio_id,
    pos.symbol,
    pos.shares,
    pos.entry_price,
    pos.current_price,
    (pos.shares * pos.current_price) as current_value,
    ((pos.current_price - pos.entry_price) * pos.shares) as unrealized_pnl,
    (((pos.current_price - pos.entry_price) / pos.entry_price) * 100) as unrealized_pnl_percent,
    pos.stop_loss,
    pos.take_profit,
    pos.entry_date,
    pos.updated_at
FROM positions pos;

CREATE VIEW v_recent_trades AS
SELECT
    t.id,
    t.portfolio_id,
    t.symbol,
    t.side,
    t.shares,
    t.price,
    t.value,
    t.commission,
    t.reason,
    t.executed_at
FROM trades t
ORDER BY t.executed_at DESC;

-- Insert default data for single user setup
INSERT INTO users (id, email, username)
VALUES ('550e8400-e29b-41d4-a716-446655440000', 'trader@localhost', 'default_trader');

INSERT INTO portfolios (id, user_id, name, initial_capital, cash, total_value)
VALUES ('550e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440000', 'Trading Simulator', 200.00, 0.00, 200.00);

-- Functions for updating timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for auto-updating timestamps
CREATE TRIGGER update_portfolios_updated_at BEFORE UPDATE ON portfolios
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_positions_updated_at BEFORE UPDATE ON positions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Function to calculate portfolio total value
CREATE OR REPLACE FUNCTION calculate_portfolio_value(p_portfolio_id UUID)
RETURNS DECIMAL(15,2) AS $$
DECLARE
    total_value DECIMAL(15,2);
    cash_amount DECIMAL(15,2);
BEGIN
    -- Get cash amount
    SELECT cash INTO cash_amount FROM portfolios WHERE id = p_portfolio_id;

    -- Calculate total position values
    SELECT COALESCE(SUM(shares * current_price), 0) INTO total_value
    FROM positions
    WHERE portfolio_id = p_portfolio_id;

    RETURN cash_amount + total_value;
END;
$$ LANGUAGE plpgsql;