"""
Base Strategy

Abstract base class for trading strategies.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Dict, List, Optional, Any
from datetime import datetime


@dataclass
class StrategySignal:
    """Signal generated by strategy"""
    symbol: str
    action: str  # BUY, SELL, HOLD
    strength: float  # 0-1
    confidence: float  # 0-1
    entry_price: Optional[float]
    stop_loss: Optional[float]
    take_profit: Optional[float]
    reasoning: str
    metadata: Dict[str, Any]
    timestamp: datetime


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.

    Strategies analyze market data and generate trading signals.
    They are pluggable components that can be swapped or combined.
    """

    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description
        self._enabled = True
        self._signals_generated = 0

    @abstractmethod
    def analyze(
        self,
        symbol: str,
        price_data: Dict[str, Any],
        technical_indicators: Dict[str, Any],
        market_context: Optional[Dict[str, Any]] = None,
    ) -> Optional[StrategySignal]:
        """
        Analyze data and generate signal.

        Args:
            symbol: Stock symbol
            price_data: OHLCV price data
            technical_indicators: Calculated indicators
            market_context: Broader market context

        Returns:
            StrategySignal if conditions met, None otherwise
        """
        pass

    @abstractmethod
    def get_required_indicators(self) -> List[str]:
        """
        List of technical indicators required by this strategy.

        Returns:
            List of indicator names
        """
        pass

    @abstractmethod
    def get_parameters(self) -> Dict[str, Any]:
        """
        Get strategy parameters for optimization.

        Returns:
            Dictionary of parameter names and current values
        """
        pass

    @abstractmethod
    def set_parameters(self, params: Dict[str, Any]):
        """
        Set strategy parameters.

        Args:
            params: Dictionary of parameter names and values
        """
        pass

    def enable(self):
        """Enable the strategy"""
        self._enabled = True

    def disable(self):
        """Disable the strategy"""
        self._enabled = False

    @property
    def is_enabled(self) -> bool:
        return self._enabled

    @property
    def signals_generated(self) -> int:
        return self._signals_generated

    def _record_signal(self):
        """Record that a signal was generated"""
        self._signals_generated += 1

    def validate_signal(self, signal: StrategySignal) -> bool:
        """
        Validate that a signal meets minimum criteria.

        Args:
            signal: Signal to validate

        Returns:
            True if valid
        """
        # Basic validation
        if not signal.symbol:
            return False

        if signal.action not in ['BUY', 'SELL', 'HOLD']:
            return False

        if not 0 <= signal.strength <= 1:
            return False

        if not 0 <= signal.confidence <= 1:
            return False

        # Price validation
        if signal.entry_price is not None and signal.entry_price <= 0:
            return False

        if signal.stop_loss is not None and signal.stop_loss <= 0:
            return False

        if signal.take_profit is not None and signal.take_profit <= 0:
            return False

        return True
